### ISSUE TITLE
Collect diurnal hyperspectral images for calibration

### ISSUE THREAD

**Issue by dlebauer** [terraref/extractors-hyperspectral#17]
@dlebauer commented on [Wed Feb 22 2017](https://github.com/terraref/computing-pipeline/issues/263)

As discussed with @remotesensinglab, @czender, @smarshall-bmr 

We need to image the spectralon targets every 15 min throughout the day, 

The first priority is a clear day
The second priority is to collect images on cloudy days

These datasets will be used in the hyperspectral calibration. 

### Details

* Scan spectralon target of varying reflectances every 15 min over the course of a clear day
* Ideally we will have 30 or 40% reflectance targets
* Files should be identified, clipped to the target area, averaged within each band
* Next step is to create an algorithm to use these for calibration as a function of zenith angle and downwelling radiance from the Environmental logger as described in #88 

### Completion Criteria

* [ ] set of files for use in calibration

**Comment by smarshall-bmr** [comment]
We are still having difficulties getting the VNIR to run in triggered mode. Would anyone object to freerunning the VNIR for this calibration? We won't have any positional data from the gantry in this mode.

**Comment by smarshall-bmr** [comment]
@czender @remotesensinglab I could use some quick input here.

**Comment by czender** [comment]
@FlyingWithJerome and I are unsure exactly what freerunning vs. triggered means. The most important thing for the calibration is that the spectralon images are directly comparable to the HS images taken everyday with the same exposure duration.

**Comment by remotesensinglab** [comment]
@smarshall-bmr would please update us the difference between  freerunning vs. triggered for image processing? That helps us to provide some feedback.

**Comment by remotesensinglab** [comment]
I think 75% or 50% reflectance targets would be ideal. The main reason for having reflectances over 1 in current calibration protocol is the overexposure. We are getting reflectance values over 1 on top canopy leaves as well, an indication of overexposure rather than the reflectance target. Higher reflectance targets may be helpful to show the dynamics of reflected light as pure vegetation/leaf reflectance can by up to 0.6.

**Comment by dlebauer** [comment]
@smarshall-bmr could you please define triggered vs in triggered mode? Is it in our documentation, or could you put it there?

**Comment by dlebauer** [comment]
@smarshall-bmr how would you propose to identify calibration files? @solmazhajmohammadi suggested naming the mission 'hyperspectral-calibration' or similar (or 'calibration' is implied by file type'.

**Comment by rachelshekar** [comment]
These files have been supplied.
