### ISSUE TITLE
dockerfile is out of date

### ISSUE THREAD

**Issue by yan130** [terraref/extractors-hyperspectral#31]
the URL for hdf5 is not work, it should be 
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.17/src/hdf5-1.8.17.tar.gz
( Thanks Sandeep for point this out)

**Comment by yan130** [comment]
Also, 
pip install netCDF4 failed when I build this time. 
can you check that?

ERROR message:

Downloading/unpacking netCDF4
  Running setup.py (path:/home/ubuntu/pyenv/build/netCDF4/setup.py) egg_info for package netCDF4
    Package hdf5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hdf5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hdf5' found
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    using netcdf library version 4.4.1
    using Cython to compile netCDF4.pyx...
    netcdf lib has group rename capability
    netcdf lib has nc_inq_path function
    netcdf lib has nc_inq_format_extended function
    netcdf lib has nc_open_mem function
    netcdf lib has cdf-5 format capability

**Comment by rachelshekar** [comment]
@dlebauer @max-zilla - who can help with this?

**Comment by dlebauer** [comment]
What dockerfile are you referring to?

**Comment by max-zilla** [comment]
I will fix, small change

**Comment by max-zilla** [comment]
This pull request should address these: https://github.com/terraref/extractors-hyperspectral/pull/32/files
